export const devTools = [
  {
    c: "Dev",
    d: "github.com",
    s: "GitHub",
    sc: "Dev",
    t: "gh",
    u: "https://github.com/search?q={{{s}}}",
  },
  {
    c: "Dev",
    d: "github.com",
    s: "GitHub Repo",
    sc: "Dev",
    t: "ghr",
    u: "https://github.com/{{{s}}}",
  },
  {
    c: "Dev",
    d: "stackoverflow.com",
    s: "Stack Overflow",
    sc: "Dev",
    t: "so",
    u: "https://stackoverflow.com/search?q={{{s}}}",
  },
  {
    c: "Dev",
    d: "npmjs.com",
    s: "npm",
    sc: "Dev",
    t: "npm",
    u: "https://www.npmjs.com/search?q={{{s}}}",
  },
  {
    c: "Dev",
    d: "docs.rs",
    s: "Rust Docs",
    sc: "Dev",
    t: "rs",
    u: "https://docs.rs/search?query={{{s}}}",
  },
  {
    c: "Dev",
    d: "dev.to",
    s: "Dev.to",
    sc: "Dev",
    t: "dev",
    u: "https://dev.to/search?q={{{s}}}",
  },
];
