export const searchEngines = [
    // Search Engines
    {
        c: "Search",
        d: "www.google.com",
        s: "Google",
        sc: "Search",
        t: "g",
        u: "https://www.google.com/search?q={{{s}}}",
    },
    {
        c: "Search",
        d: "www.duckduckgo.com",
        s: "DuckDuckGo",
        sc: "Search",
        t: "dd",
        u: "https://duckduckgo.com/?q={{{s}}}",
    },
    {
        c: "Search",
        d: "www.bing.com",
        s: "Bing",
        sc: "Search",
        t: "b",
        u: "https://www.bing.com/search?q={{{s}}}",
    },
    {
        c: "Search",
        d: "www.startpage.com",
        s: "Startpage",
        sc: "Search",
        t: "sp",
        u: "https://www.startpage.com/do/search?q={{{s}}}",
    },
    {
        c: "Search",
        d: "www.ecosia.org",
        s: "Ecosia",
        sc: "Search",
        t: "eco",
        u: "https://www.ecosia.org/search?q={{{s}}}",
    },
    {
        c: "Search",
        d: "kagi.com",
        s: "Kagi",
        sc: "Search",
        t: "kg",
        u: "https://kagi.com/search?q={{{s}}}",
    },
    {
        c: "Search",
        d: "search.brave.com",
        s: "Brave Search",
        sc: "Search",
        t: "br",
        u: "https://search.brave.com/search?q={{{s}}}",
    },
    {
        c: "Search",
        d: "search.surfshark.com",
        s: "Surfshark Search",
        sc: "Search",
        t: "sf",
        u: "https://search.surfshark.com/results?query={{{s}}}",
    },
    {
        c: "Search",
        d: "www.qwant.com",
        s: "Qwant",
        sc: "Search",
        t: "qw",
        u: "https://www.qwant.com/?q={{{s}}}",
    },
];
