export const streaming = [
  {
    c: "Streaming",
    d: "movieland.eliasnau.dev",
    s: "MovieLand",
    sc: "Infomrmation",
    t: "movie",
    u: "https://movieland.eliasnau.dev/search?query={{{s}}}",
  },
  {
    c: "Streaming",
    d: "netflix.com",
    s: "Netflix",
    sc: "Streaming",
    t: "nf",
    u: "https://www.netflix.com/search?q={{{s}}}",
  },
  {
    c: "Streaming",
    d: "amazon.com",
    s: "Prime Video",
    sc: "Streaming",
    t: "pv",
    u: "https://www.amazon.com/s?k={{{s}}}&i=instant-video",
  },
  {
    c: "Streaming",
    d: "www.twitch.tv",
    s: "Twitch",
    sc: "Streaming",
    t: "tw",
    u: "https://www.twitch.tv/search?term={{{s}}}",
  },
  {
    c: "Streaming",
    d: "www.imdb.com",
    s: "IMDB",
    sc: "Information",
    t: "imdb",
    u: "https://www.imdb.com/find?q={{{s}}}",
  },
];
