// This file was (mostly) ripped from https://duckduckgo.com/bang.js

export const bangs = [
  {
    c: "Search",
    d: "www.google.com",
    s: "Google",
    sc: "Search",
    t: "g",
    u: "https://www.google.com/search?q={{{s}}}",
  },
  {
    c: "Wiki",
    d: "www.wikipedia.org",
    s: "Wikipedia",
    sc: "Wiki",
    t: "w",
    u: "https://en.wikipedia.org/wiki/{{{s}}}",
  },
  {
    c: "Gaming",
    d: "store.steampowered.com",
    s: "Steam",
    sc: "Gaming",
    t: "ste",
    u: "https://store.steampowered.com/search/?term={{{s}}}",
  },
  {
    c: "Social",
    d: "twitter.com",
    s: "X (Twitter)",
    sc: "Social",
    t: "x",
    u: "https://twitter.com/search?q={{{s}}}",
  },
  {
    c: "Shopping",
    d: "www.ebay.com",
    s: "eBay",
    sc: "Shopping",
    t: "e",
    u: "https://www.ebay.com/sch/i.html?_nkw={{{s}}}",
  },
  {
    c: "Dev",
    d: "github.com",
    s: "GitHub",
    sc: "Dev",
    t: "gh",
    u: "https://github.com/search?q={{{s}}}",
  },
  {
    c: "Dev",
    d: "github.com",
    s: "GitHub Repo",
    sc: "Dev",
    t: "ghr",
    u: "https://github.com/{{{s}}}",
  },
  {
    c: "Streaming",
    d: "netflix.com",
    s: "Netflix",
    sc: "Streaming",
    t: "nf",
    u: "https://www.netflix.com/search?q={{{s}}}",
  },
  {
    c: "Dev",
    d: "stackoverflow.com",
    s: "Stack Overflow",
    sc: "Dev",
    t: "so",
    u: "https://stackoverflow.com/search?q={{{s}}}",
  },
  {
    c: "Streaming",
    d: "amazon.com",
    s: "Prime Video",
    sc: "Streaming",
    t: "pv",
    u: "https://www.amazon.com/s?k={{{s}}}&i=instant-video",
  },
  {
    c: "AI",
    d: "www.t3.chat",
    s: "T3 Chat",
    sc: "AI",
    t: "t3",
    u: "https://www.t3.chat/new?q={{{s}}}",
  },
  {
    c: "Video",
    d: "youtube.com",
    s: "YouTube",
    sc: "Video",
    t: "yt",
    u: "https://www.youtube.com/results?search_query={{{s}}}",
  },
  {
    c: "Maps",
    d: "maps.google.com",
    s: "Google Maps",
    sc: "Maps",
    t: "maps",
    u: "https://www.google.com/maps/search/{{{s}}}",
  },
  {
    c: "Dev",
    d: "npmjs.com",
    s: "npm",
    sc: "Dev",
    t: "npm",
    u: "https://www.npmjs.com/search?q={{{s}}}",
  },
  {
    c: "Shopping",
    d: "amazon.com",
    s: "Amazon",
    sc: "Shopping",
    t: "a",
    u: "https://www.amazon.com/s?k={{{s}}}",
  }
];