// This file was (mostly) ripped from https://duckduckgo.com/bang.js

export const bangs = [
  {
    c: "Search",
    d: "www.google.com",
    s: "Google",
    sc: "Search",
    t: "g",
    u: "https://www.google.com/search?q={{{s}}}",
  },
  {
    c: "Wiki",
    d: "www.wikipedia.org",
    s: "Wikipedia",
    sc: "Wiki",
    t: "w",
    u: "https://en.wikipedia.org/wiki/{{{s}}}",
  },
  {
    c: "Gaming",
    d: "store.steampowered.com",
    s: "Steam",
    sc: "Gaming",
    t: "ste",
    u: "https://store.steampowered.com/search/?term={{{s}}}",
  },
  {
    c: "Social",
    d: "twitter.com",
    s: "X (Twitter)",
    sc: "Social",
    t: "x",
    u: "https://twitter.com/search?q={{{s}}}",
  },
  {
    c: "Shopping",
    d: "www.ebay.com",
    s: "eBay",
    sc: "Shopping",
    t: "e",
    u: "https://www.ebay.com/sch/i.html?_nkw={{{s}}}",
  },
  {
    c: "Dev",
    d: "github.com",
    s: "GitHub",
    sc: "Dev",
    t: "gh",
    u: "https://github.com/search?q={{{s}}}",
  },
  {
    c: "Dev",
    d: "github.com",
    s: "GitHub Repo",
    sc: "Dev",
    t: "ghr",
    u: "https://github.com/{{{s}}}",
  },
  {
    c: "Streaming",
    d: "netflix.com",
    s: "Netflix",
    sc: "Streaming",
    t: "nf",
    u: "https://www.netflix.com/search?q={{{s}}}",
  },
  {
    c: "Dev",
    d: "stackoverflow.com",
    s: "Stack Overflow",
    sc: "Dev",
    t: "so",
    u: "https://stackoverflow.com/search?q={{{s}}}",
  },
  {
    c: "Streaming",
    d: "amazon.com",
    s: "Prime Video",
    sc: "Streaming",
    t: "pv",
    u: "https://www.amazon.com/s?k={{{s}}}&i=instant-video",
  },
  {
    c: "AI",
    d: "www.t3.chat",
    s: "T3 Chat",
    sc: "AI",
    t: "t3",
    u: "https://www.t3.chat/new?q={{{s}}}",
  },
  {
    c: "AI",
    d: "chat.openai.com",
    s: "ChatGPT",
    sc: "AI",
    t: "gpt",
    u: "https://chat.openai.com/?q={{{s}}}",
  },
  {
    c: "AI",
    d: "claude.ai",
    s: "Claude",
    sc: "AI",
    t: "cla",
    u: "https://claude.ai/new?q={{{s}}}",
  },
  {
    c: "AI",
    d: "perplexity.ai",
    s: "Perplexity",
    sc: "AI",
    t: "per",
    u: "https://www.perplexity.ai/search?q={{{s}}}",
  },
  {
    c: "Video",
    d: "youtube.com",
    s: "YouTube",
    sc: "Video",
    t: "yt",
    u: "https://www.youtube.com/results?search_query={{{s}}}",
  },
  {
    c: "Maps",
    d: "maps.google.com",
    s: "Google Maps",
    sc: "Maps",
    t: "maps",
    u: "https://www.google.com/maps/search/{{{s}}}",
  },
  {
    c: "Dev",
    d: "npmjs.com",
    s: "npm",
    sc: "Dev",
    t: "npm",
    u: "https://www.npmjs.com/search?q={{{s}}}",
  },
  {
    c: "Shopping",
    d: "amazon.com",
    s: "Amazon",
    sc: "Shopping",
    t: "a",
    u: "https://www.amazon.com/s?k={{{s}}}",
  },
  {
    c: "Dev",
    d: "docs.rs",
    s: "Rust Docs",
    sc: "Dev",
    t: "rs",
    u: "https://docs.rs/search?query={{{s}}}",
  },
  {
    c: "Music",
    d: "spotify.com",
    s: "Spotify",
    sc: "Music",
    t: "sp",
    u: "https://open.spotify.com/search/{{{s}}}",
  },
  {
    c: "Music",
    d: "soundcloud.com",
    s: "SoundCloud",
    sc: "Music",
    t: "sc",
    u: "https://soundcloud.com/search?q={{{s}}}",
  },
  {
    c: "Shopping",
    d: "aliexpress.com",
    s: "AliExpress",
    sc: "Shopping",
    t: "ali",
    u: "https://www.aliexpress.com/wholesale?SearchText={{{s}}}",
  },
  {
    c: "Social",
    d: "reddit.com",
    s: "Reddit",
    sc: "Social",
    t: "r",
    u: "https://www.reddit.com/search/?q={{{s}}}",
  },
  {
    c: "Images",
    d: "unsplash.com",
    s: "Unsplash",
    sc: "Images",
    t: "un",
    u: "https://unsplash.com/s/photos/{{{s}}}",
  },
  {
    c: "Translation",
    d: "translate.google.com",
    s: "Google Translate",
    sc: "Tools",
    t: "tr",
    u: "https://translate.google.com/?text={{{s}}}",
  },
  {
    c: "Images",
    d: "images.google.com",
    s: "Google Images",
    sc: "Images",
    t: "gi",
    u: "https://www.google.com/search?tbm=isch&q={{{s}}}",
  }
];